package com.matete.agentmanage.model;

import com.matete.agentmanage.model.base.BaseFunctionRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FunctionRole extends BaseFunctionRole<FunctionRole> {
	public static final FunctionRole dao = new FunctionRole().dao();
}
