package com.matete.agentmanage.model;

import com.matete.agentmanage.model.base.BaseMemberAgent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberAgent extends BaseMemberAgent<MemberAgent> {
	public static final MemberAgent dao = new MemberAgent().dao();
}
