package com.matete.agentmanage.model;

import com.matete.agentmanage.model.base.BasePlayer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Player extends BasePlayer<Player> {
	public static final Player dao = new Player().dao();
}
