package com.matete.agentmanage.model;

import com.matete.agentmanage.model.base.BaseProperty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Property extends BaseProperty<Property> {
	public static final Property dao = new Property().dao();
}
