package com.matete.agentmanage.model;

import com.matete.agentmanage.model.base.BaseRecordRecharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecordRecharge extends BaseRecordRecharge<RecordRecharge> {
	public static final RecordRecharge dao = new RecordRecharge().dao();
}
