package com.matete.agentmanage.model;

import com.matete.agentmanage.model.base.BaseRecordLogin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecordLogin extends BaseRecordLogin<RecordLogin> {
	public static final RecordLogin dao = new RecordLogin().dao();
}
