package com.matete.agentmanage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePlayer<M extends BasePlayer<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setAccount(java.lang.String account) {
		set("account", account);
		return (M)this;
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setHead(java.lang.String head) {
		set("head", head);
		return (M)this;
	}

	public java.lang.String getHead() {
		return get("head");
	}

	public M setCard(java.lang.Integer card) {
		set("card", card);
		return (M)this;
	}

	public java.lang.Integer getCard() {
		return get("card");
	}

	public M setCardConsume(java.lang.Integer cardConsume) {
		set("cardConsume", cardConsume);
		return (M)this;
	}

	public java.lang.Integer getCardConsume() {
		return get("cardConsume");
	}

	public M setRoom(java.lang.Integer room) {
		set("room", room);
		return (M)this;
	}

	public java.lang.Integer getRoom() {
		return get("room");
	}

	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M)this;
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public M setPoints(java.lang.Long points) {
		set("points", points);
		return (M)this;
	}

	public java.lang.Long getPoints() {
		return get("points");
	}

	public M setTotal(java.lang.Integer total) {
		set("total", total);
		return (M)this;
	}

	public java.lang.Integer getTotal() {
		return get("total");
	}

	public M setForbidTime(java.lang.String forbidTime) {
		set("forbidTime", forbidTime);
		return (M)this;
	}

	public java.lang.String getForbidTime() {
		return get("forbidTime");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public M setHaveNewEmail(java.lang.Integer haveNewEmail) {
		set("haveNewEmail", haveNewEmail);
		return (M)this;
	}

	public java.lang.Integer getHaveNewEmail() {
		return get("haveNewEmail");
	}

	public M setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
		return (M)this;
	}

	public java.lang.String getUnionid() {
		return get("unionid");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public M setCountry(java.lang.String country) {
		set("country", country);
		return (M)this;
	}

	public java.lang.String getCountry() {
		return get("country");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setLoginTime(java.util.Date loginTime) {
		set("loginTime", loginTime);
		return (M)this;
	}

	public java.util.Date getLoginTime() {
		return get("loginTime");
	}

	public M setChannel(java.lang.Integer channel) {
		set("channel", channel);
		return (M)this;
	}

	public java.lang.Integer getChannel() {
		return get("channel");
	}

	public M setVersion(java.lang.Integer version) {
		set("version", version);
		return (M)this;
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public M setInviteId(java.lang.Integer inviteId) {
		set("inviteId", inviteId);
		return (M)this;
	}

	public java.lang.Integer getInviteId() {
		return get("inviteId");
	}

}
