package com.matete.agentmanage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAccountuserinfo<M extends BaseAccountuserinfo<M>> extends Model<M> implements IBean {

	public M setGameID(java.lang.Integer GameID) {
		set("GameID", GameID);
		return (M)this;
	}

	public java.lang.Integer getGameID() {
		return get("GameID");
	}

	public M setSecurityID(java.lang.Integer SecurityID) {
		set("SecurityID", SecurityID);
		return (M)this;
	}

	public java.lang.Integer getSecurityID() {
		return get("SecurityID");
	}

	public M setSecretAnswer(java.lang.String SecretAnswer) {
		set("SecretAnswer", SecretAnswer);
		return (M)this;
	}

	public java.lang.String getSecretAnswer() {
		return get("SecretAnswer");
	}

	public M setGeneralizedID(java.lang.Integer GeneralizedID) {
		set("GeneralizedID", GeneralizedID);
		return (M)this;
	}

	public java.lang.Integer getGeneralizedID() {
		return get("GeneralizedID");
	}

	public M setNickName(java.lang.String NickName) {
		set("NickName", NickName);
		return (M)this;
	}

	public java.lang.String getNickName() {
		return get("NickName");
	}

	public M setAccount(java.lang.String Account) {
		set("Account", Account);
		return (M)this;
	}

	public java.lang.String getAccount() {
		return get("Account");
	}

	public M setIdentityID(java.lang.String IdentityID) {
		set("IdentityID", IdentityID);
		return (M)this;
	}

	public java.lang.String getIdentityID() {
		return get("IdentityID");
	}

	public M setName(java.lang.String Name) {
		set("Name", Name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("Name");
	}

	public M setLastLoginTime(java.lang.String LastLoginTime) {
		set("LastLoginTime", LastLoginTime);
		return (M)this;
	}

	public java.lang.String getLastLoginTime() {
		return get("LastLoginTime");
	}

	public M setOfflineTime(java.lang.String OfflineTime) {
		set("OfflineTime", OfflineTime);
		return (M)this;
	}

	public java.lang.String getOfflineTime() {
		return get("OfflineTime");
	}

	public M setIsAndroid(java.lang.Integer isAndroid) {
		set("isAndroid", isAndroid);
		return (M)this;
	}

	public java.lang.Integer getIsAndroid() {
		return get("isAndroid");
	}

	public M setLastLoginIp(java.lang.String LastLoginIp) {
		set("LastLoginIp", LastLoginIp);
		return (M)this;
	}

	public java.lang.String getLastLoginIp() {
		return get("LastLoginIp");
	}

	public M setRegistrationTime(java.lang.String RegistrationTime) {
		set("RegistrationTime", RegistrationTime);
		return (M)this;
	}

	public java.lang.String getRegistrationTime() {
		return get("RegistrationTime");
	}

	public M setRegisterDevice(java.lang.String RegisterDevice) {
		set("RegisterDevice", RegisterDevice);
		return (M)this;
	}

	public java.lang.String getRegisterDevice() {
		return get("RegisterDevice");
	}

	public M setStateID(java.lang.Integer StateID) {
		set("StateID", StateID);
		return (M)this;
	}

	public java.lang.Integer getStateID() {
		return get("StateID");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public M setLoginDevice(java.lang.Integer loginDevice) {
		set("loginDevice", loginDevice);
		return (M)this;
	}

	public java.lang.Integer getLoginDevice() {
		return get("loginDevice");
	}

	public M setServiceip(java.lang.String serviceip) {
		set("serviceip", serviceip);
		return (M)this;
	}

	public java.lang.String getServiceip() {
		return get("serviceip");
	}

	public M setServiceport(java.lang.Integer serviceport) {
		set("serviceport", serviceport);
		return (M)this;
	}

	public java.lang.Integer getServiceport() {
		return get("serviceport");
	}

	public M setBackyards(java.lang.Integer backyards) {
		set("backyards", backyards);
		return (M)this;
	}

	public java.lang.Integer getBackyards() {
		return get("backyards");
	}

	public M setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
		return (M)this;
	}

	public java.lang.String getAvatar() {
		return get("avatar");
	}

}
