package com.matete.agentmanage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSystemannouncement<M extends BaseSystemannouncement<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public M setDate(java.lang.Integer date) {
		set("date", date);
		return (M)this;
	}

	public java.lang.Integer getDate() {
		return get("date");
	}

	public M setUser(java.lang.String user) {
		set("user", user);
		return (M)this;
	}

	public java.lang.String getUser() {
		return get("user");
	}

	public M setMessage(java.lang.String message) {
		set("message", message);
		return (M)this;
	}

	public java.lang.String getMessage() {
		return get("message");
	}

}
