package com.matete.agentmanage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProperty<M extends BaseProperty<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public M setPropertyKey(java.lang.String PropertyKey) {
		set("PropertyKey", PropertyKey);
		return (M)this;
	}

	public java.lang.String getPropertyKey() {
		return get("PropertyKey");
	}

	public M setPropertyValue(java.lang.Integer PropertyValue) {
		set("PropertyValue", PropertyValue);
		return (M)this;
	}

	public java.lang.Integer getPropertyValue() {
		return get("PropertyValue");
	}

	public M setPropertyName(java.lang.String PropertyName) {
		set("PropertyName", PropertyName);
		return (M)this;
	}

	public java.lang.String getPropertyName() {
		return get("PropertyName");
	}

}
