package com.matete.agentmanage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public M setRoleID(java.lang.Integer RoleID) {
		set("RoleID", RoleID);
		return (M)this;
	}

	public java.lang.Integer getRoleID() {
		return get("RoleID");
	}

	public M setRoleName(java.lang.String RoleName) {
		set("RoleName", RoleName);
		return (M)this;
	}

	public java.lang.String getRoleName() {
		return get("RoleName");
	}

}
