package com.matete.agentmanage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFunctionRole<M extends BaseFunctionRole<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public M setRoleID(java.lang.Integer RoleID) {
		set("RoleID", RoleID);
		return (M)this;
	}

	public java.lang.Integer getRoleID() {
		return get("RoleID");
	}

	public M setFunctionID(java.lang.Integer FunctionID) {
		set("FunctionID", FunctionID);
		return (M)this;
	}

	public java.lang.Integer getFunctionID() {
		return get("FunctionID");
	}

}
