package com.matete.agentmanage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMemberAgent<M extends BaseMemberAgent<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public M setGameID(java.lang.Integer GameID) {
		set("GameID", GameID);
		return (M)this;
	}

	public java.lang.Integer getGameID() {
		return get("GameID");
	}

	public M setAgentID(java.lang.Integer agentID) {
		set("agentID", agentID);
		return (M)this;
	}

	public java.lang.Integer getAgentID() {
		return get("agentID");
	}

	public M setBindingtime(java.util.Date bindingtime) {
		set("bindingtime", bindingtime);
		return (M)this;
	}

	public java.util.Date getBindingtime() {
		return get("bindingtime");
	}

}
