package com.matete.agentmanage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRecordLogin<M extends BaseRecordLogin<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public M setAgentId(java.lang.Integer AgentId) {
		set("AgentId", AgentId);
		return (M)this;
	}

	public java.lang.Integer getAgentId() {
		return get("AgentId");
	}

	public M setLoginIp(java.lang.String LoginIp) {
		set("LoginIp", LoginIp);
		return (M)this;
	}

	public java.lang.String getLoginIp() {
		return get("LoginIp");
	}

	public M setDeviceId(java.lang.Integer DeviceId) {
		set("DeviceId", DeviceId);
		return (M)this;
	}

	public java.lang.Integer getDeviceId() {
		return get("DeviceId");
	}

	public M setPlace(java.lang.String Place) {
		set("Place", Place);
		return (M)this;
	}

	public java.lang.String getPlace() {
		return get("Place");
	}

	public M setCreateTime(java.util.Date CreateTime) {
		set("CreateTime", CreateTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("CreateTime");
	}

}
